Add Support For Thin Jars in GAE (#10420)
* add support for thin jar in gae

Only adds to maven build; work in progress

* correcting mistake introduced in a pervious pull request

A previous pull request incorrectly removes the com.google.cloud.tools when gaeCloudSQLInstanceNeeded is set to false

#10362

* add correct handlers for retrieving static files

* remove bootWar from gradle

The new GAE with Java 11 builds on JAR; this has been done on the maven side.

* correcting mistake introduced in a pervious pull request

A previous pull request incorrectly removes the com.google.cloud.tools when gaeCloudSQLInstanceNeeded is set to false

* replace deprecated value "project" by "projectId"

* testing with cloudsql; change string to single quotes

If this is not done the following error is created;

yntaxError: Multi-line double-quoted string needs to be sufficiently indented (16:14)
  14 |     datasource:
  15 |         type: com.zaxxer.hikari.HikariDataSource
> 16 |         url: "jdbc:mysql://google/mysql?cloudSqlInstance=abstract-block-253023:us-central1:testjhipster
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Add copyright information

* add mainclass name instead of basename

* add gradle support for unjaring the original jar

This adds Gradle side support for thin jars

* missing symbol from previous commit

* remove the original jar as per discussion

* minor bug fix per code review

* add max heap size to entrypoint field in app.yaml

* Revert Xmx change

* correction of the url strings

* remove whitespaces in project ID

* simplify the prod-gae profile definition

* thin jar generation support for maven

* thin jar generation support for gradle

* adjustments to the maven and gradle deployment commands

* add thinResolve step before staging

* prettier issue fix

* add error code checking for gcloud

- gcloud seems to print out info messages to the error stream as well. We need to check whether it's an actual error

* add trim to remove unnecessary newline and remove silent mode for prompt in order to trigger cloud sql api

* fix the trim line more elegantly

* add missing maven dependency

* refactor code to include application-prod-gae.yml file regardless of Cloud SQL

- this makes sure the correct port environment variable is passed whether the user chose to use cloud sql or not.

* fix dependency problem (similar to #9175) to get rid of the clean option

* add dependency before the check for cloud sql

* changed per code review