Added missing authorizedRoles attribute
Retrieving new entities would cause this JavaScript error:

TypeError: Cannot read property 'authorizedRoles' of undefined at http://localhost:8080/scripts/app.js:119:54 at Scope.$broadcast (http://localhost:8080/bower_components/angular/angular.js:12691:28) at updateRoute (http://localhost:8080/bower_components/angular-route/angular-route.js:499:20) at Scope.$broadcast (http://localhost:8080/bower_components/angular/angular.js:12691:28) at afterLocationChange (http://localhost:8080/bower_components/angular/angular.js:9625:18) at http://localhost:8080/bower_components/angular/angular.js:9613:13 at Scope.$eval (http://localhost:8080/bower_components/angular/angular.js:12412:28) at Scope.$digest (http://localhost:8080/bower_components/angular/angular.js:12224:31) at Scope.$apply (http://localhost:8080/bower_components/angular/angular.js:12516:24) at HTMLBodyElement.<anonymous> (http://localhost:8080/bower_components/angular/angular.js:9567:22) angular.js:9778