Change KR to kr to fix test
Testing language: kr-Latin-kr
getJavaLocale: kr-Latin-kr
Error:  Tests run: 10, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.58 s <<< FAILURE! - in tech.jhipster.sample.service.MailServiceIT
Error:  tech.jhipster.sample.service.MailServiceIT.testSendLocalizedEmailForAllSupportedLanguages  Time elapsed: 0.287 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.net.URL.getFile()" because "resource" is null
	at tech.jhipster.sample.service.MailServiceIT.testSendLocalizedEmailForAllSupportedLanguages(MailServiceIT.java:258)