A blocking call caused java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId on the Cassandra integration tests