fix :  Updating Helm Chart repository for stable and incubator
As, Helm chart repositories are moved from
 "https://kubernetes-charts-incubator.storage.googleapis.com" and "https://kubernetes-charts.storage.googleapis.com" to
 "https://charts.helm.sh/incubator" and "https://charts.helm.sh/stable" respectively so updating.

Also , this suggestion is given by "Helm Cli" upon running
"helm dependency build " on generated helm charts by "kubernetes-helm" sub-generator of "jhipster-generator".

`
Error: repo "https://kubernetes-charts.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/stable" instead
Error: repo "https://kubernetes-charts-incubator.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/incubator" instead
`

Signed-off-by: Pratik raj <rajpratik71@gmail.com>