Fix compiler error
jhi-missing-translation.config.ts(3,14): error TS2420: Class 'JhiMissingTranslationHandler' incorrectly implements interface 'MissingTranslationHandler'.