testing with cloudsql; change string to single quotes
If this is not done the following error is created;

yntaxError: Multi-line double-quoted string needs to be sufficiently indented (16:14)
  14 |     datasource:
  15 |         type: com.zaxxer.hikari.HikariDataSource
> 16 |         url: "jdbc:mysql://google/mysql?cloudSqlInstance=abstract-block-253023:us-central1:testjhipster
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^