Fixing the js problem "ERROR TypeError: _this.authServerProvider.logout is not a function     at CatchSubscriber.eval [as selector] (VM8171 auth-expired.interceptor.ts:42)     at CatchSubscriber.error (VM7476 catch.js:104)..."
Which caused by wrong dependency declarations - which cause that in AuthExpiredInterceptor
 the loginServiceModal is null, and authServerProvider is actually a JhiEventManager.
Unfortunately injecting the AuthServerProvider would cause a cyclic dependency, so the Injector is used,
and the AuthServerProvider is acquired lazily